<?php

/**
 * Implements hook_permission().
 */
function back_to_parent_permission() {
  return array(
    'administer btp' => array(
      'title' => t('Administer Back to Parent'),
      'description' => t('Administer the general settings for Back to Parent links'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function back_to_parent_menu() {
  $items['admin/config/user-interface/back-to-parent'] = array(
    'title' => t('Back to Parent'),
    'description' => t('Configure the "Back to Parent" link blocks and settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('back_to_parent_settings'),
    'access arguments' => array('administer btp'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'back_to_parent.admin.inc',
    'file path' => drupal_get_path('module', 'back_to_parent'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function back_to_parent_theme() {
  return array(
    'back_to_parent_block' => array(
      'variables' => array(
        'back_to_parent_link' => NULL,
      ),
      'template' => 'templates/back_to_parent_block',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function back_to_parent_block_info() {
  global $language;
  $lang = ($language->language == 'en') ? '' : '_' . $language->language;

  $max_to_display = variable_get('number_of_back_to_parent_blocks' . $lang, 1);
  $blocks = array();
  for($i = 1; $i <= $max_to_display; $i++) {
    $blocks['back_to_parent_link_' . $i] = array(
      'info' => t('Back to Parent Link - ' . $i),
      'cache' => DRUPAL_CACHE_GLOBAL,
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function back_to_parent_block_view($delta = '') {
  global $language;
  $lang = ($language->language == 'en') ? '' : '_' . $language->language;

  $max_to_display = variable_get('number_of_back_to_parent_blocks' . $lang, 1);
  $block = array();
  for($i = 1; $i <= $max_to_display; $i++) {
    switch ($delta) {
      case 'back_to_parent_link_' . $i:
        $prefix = variable_get('btp_block' . $i . '_prefix' . $lang);
        $prefix = (!empty($prefix)) ? $prefix . ' ' : '';
        $suffix = variable_get('btp_block' . $i . '_suffix' . $lang);
        $suffix = (!empty($suffix)) ? ' ' . $suffix : '';

        $plid_item = back_to_parent_item();
        if (!empty($plid_item)) {
          $parent_link = l($prefix . $plid_item['title'] . $suffix, $plid_item['href'], array('attributes' => array('class' => 'back-to-link')));
          $block['subject'] = '';
          $block['content'] = array(
            '#theme' => 'back_to_parent_block',
            '#back_to_parent_link' => $parent_link,
          );
        } else {
          $parent_link = NULL;
          $block['subject'] = NULL;
          $block['content'] = NULL;
        }
      break;
    }
  }

  return $block;
}

/**
 * Implements hook_block_view().
 */
function back_to_parent_block_configure($delta = '') {
  global $language;
  $lang = ($language->language == 'en') ? '' : '_' . $language->language;

  $max_to_display = variable_get('number_of_back_to_parent_blocks' . $lang, 1);
  $form = array();
  for($i = 1; $i <= $max_to_display; $i++) {
    switch ($delta) {
      case 'back_to_parent_link_' . $i:
        $form['btp_block' . $i . '_prefix' . $lang] = array(
          '#type' => 'text',
          '#title' => t('Link Prefix'),
          '#default_value' => variable_get('btp_block' . $i . '_prefix' . $lang, 'Back to'),
        );
        $form['btp_block' . $i . '_suffix' . $lang] = array(
          '#type' => 'text',
          '#title' => t('Link Prefix'),
          '#default_value' => variable_get('btp_block' . $i . '_suffix' . $lang, ''),
        );
      break;
    }
  }

  return $form;
}

/**
 * Implements hook_block_view().
 */
function back_to_parent_block_save($delta = '', $edit = array()) {
  global $language;
  $lang = ($language->language == 'en') ? '' : '_' . $language->language;

  $max_to_display = variable_get('number_of_back_to_parent_blocks' . $lang, 1);
  for($i = 1; $i <= $max_to_display; $i++) {
    switch ($delta) {
      case 'back_to_parent_link_' . $i:
        variable_get('btp_block' . $i . '_prefix' . $lang, $edit['btp_block' . $i . '_prefix' . $lang]);
        variable_get('btp_block' . $i . '_suffix' . $lang, $edit['btp_block' . $i . '_suffix' . $lang]);
      break;
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function back_to_parent_preprocess_page(&$vars) {
  $parent_link_item = back_to_parent_item();
  if (!empty($parent_link_item)) {
    $attributes = array('attributes' => array('class' => array('back-to-parent', 'link'),),);
    $back_to_parent_link = l($parent_link_item['link_title'], $parent_link_item['link_path'], $attributes);
    $vars['back_to_parent_link'] = $back_to_parent_link;
  }
}

/**
 * Return an array of the current pages closest parent link.
 */
function back_to_parent_item() {
  // We need the current active trail of the current page
  $trail = menu_get_active_trail();

  // If a trail exists,
  // we need the last one (closest parent to the current page).
  if (isset($trail)) {
    $current_menu_item = array_pop($trail);
  } else {
    $current_menu_item = NULL;
  }

  // If there is a parent, we need its id.
  if ((!empty($current_menu_item)) && (isset($current_menu_item['plid']))) {
    $plid = $current_menu_item['plid'];
  } else {
    $plid = NULL;
  }

  // If there is a parent link id and it does not equal 0,
  // use it to load the parent menu item array.
  if ((!empty($plid)) && ($plid != 0)) {
    $plid_item = menu_link_load($plid);
  } else {
    $plid_item = NULL;
  }

  return $plid_item;
}
